version: '3.8'

services:
  nginx:
    build: ..
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      # Optional: Uncomment to use a custom config
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro